%% MATLAB Code from Sensor Array Analyzer App
% Generated by MATLAB 25.2 and Phased Array System Toolbox 25.2
% Generated on 30-Mar-2026 13:31:57

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',9,'ArrayAxis','y');
Array.ElementSpacing = 0.5*0.03;
Array.Taper = ones(1,9).';

% Create a cosine antenna element
Elem = phased.CosineAntennaElement;
Elem.CosinePower = [2.25 2.25];
Elem.FrequencyRange = [0 10000000000];
Array.Element = Elem;

% Frequencies and Propagation Speed
Frequency = 10000000000;
PropagationSpeed = 300000000;

% Parameters
f = Frequency;
lambda = PropagationSpeed / f;
d = Array.ElementSpacing;
numElements = getNumElements(Array);
element_idx = (0 : numElements-1)';

% Scan setup
theta_steer = 0 : 15 : 60;
theta_scan = -90 : 0.1 : 90;
bits_to_test = [2, 3, 4]; % Parts c, d, e

% Symbolic setup for solver
syms fr positive

%% Loop through Quantization Levels
for b = 1:length(bits_to_test)
    num_bits = bits_to_test(b);
    num_states = 2^num_bits;

    step_size = 360 / num_states;
    half_step_rad = deg2rad(step_size / 2);

    fprintf('Simulating %d-bit quantization...\n', num_bits);
    
    sv = phased.SteeringVector('SensorArray', Array,...
        'PropagationSpeed', PropagationSpeed, ...
        'NumPhaseShifterBits', num_bits);

    peak_gains = zeros(size(theta_steer));
    errors = zeros(size(theta_steer));
    patterns_to_plot = zeros(length(theta_steer), length(theta_scan)); 
    all_A = []; 
    all_P = []; 

    for ti = 1:length(theta_steer)
        w_quantized = sv(Frequency, [theta_steer(ti); 0]);
        w_shifted = w_quantized .* exp(1i * half_step_rad);
        w = zeros(numElements, 1);

        for el = 1:numElements
            % Quantize the required phase
            phi_req_deg = rad2deg(angle(w_shifted(el)));

            % Solve for fr that achieves phi_req at 10 GHz within [8, 12] GHz
            eqn    = ((2*angle((2 + fr)./(fr^2 - f^2 + 1i*0.05*fr*f)) + pi)*180/pi) ...
                     == phi_req_deg;
            assume(fr,'positive');
            fr_sol = (vpasolve(eqn,fr));

            if fr_sol < 8e9
                fr_sol = 8e9;
            elseif fr_sol > 12e9
                fr_sol = 12e9;
            end

            fprintf('    El %d:, phase=%.2f, fr=%.2f\n', el, phi_req_deg, fr_sol);

            % Compute coupled weight
            R_el = (2 + fr_sol) / (fr_sol^2 - f^2 + 1i*0.05*fr_sol*f);
            A = 1 - abs(R_el) * 100e6;
            P = 2 * angle(R_el) + pi;
            w(el) = A * exp(1i * P);
            
            % Save for Lorentzian plot
            all_A(end+1) = A; 
            all_P(end+1) = rad2deg(P);
        end
        
        % Calculate peak and actual pointing angle
        % Peak directivity at intended steering angle — absolute dBi
        peak_gains(ti) = pattern(Array, Frequency, theta_steer(ti), 0, ...
                             'PropagationSpeed', PropagationSpeed, ...
                             'Type', 'directivity', ...
                             'weights', w);
    
        % Full pattern in powerdb for polar plot
        AF_total               = pattern(Array, Frequency, theta_scan, 0, ...
                                     'PropagationSpeed', PropagationSpeed, ...
                                     'Type', 'powerdb', ...
                                     'weights', w).';
        [main_peak, peak_idx]  = max(AF_total);
        actual_deg(ti)         = theta_scan(peak_idx);
        errors(ti)             = abs(theta_steer(ti) - actual_deg(ti));
        patterns_to_plot(ti,:) = AF_total;

        [psl, ~] = sidelobelevel(AF_total);
        sll_vals(ti) = psl; 
    end
    
    sll_all_bits(b, :) = sll_vals;

    %% Plotting Results for this Bit-level
    figure('Name', sprintf('%d-Bit Summary', num_bits), 'Color', 'w', 'Position', [100 100 1200 400]);
    
    %% 1. Pointing Error
    subplot(1,4,1);
    scatter(theta_steer, errors, 80, 'filled', 'MarkerFaceColor', [0.15 0.30 0.45]); grid on;
    title('Pointing Error'); xlabel('\theta_{intended} [deg]'); ylabel('Error [deg]');

    %% 2. Polar Pattern
    ax_pol = subplot(1,4,2); 
    pos = get(ax_pol, 'Position'); % Get subplot position
    delete(ax_pol); % Remove standard axes
    pax = polaraxes('Position', pos); % Create proper polar axes
    hold(pax, 'on');
    colors = turbo(length(theta_steer));
    
    % Reference max for normalization (0-degree beam peak)
    ref_max = max(patterns_to_plot(1,:));
    
    for ti = 1 : length(theta_steer)
        pattern_norm = patterns_to_plot(ti,:) - ref_max;
        polarplot(pax, deg2rad(theta_scan), pattern_norm, ...
            'LineWidth', 1.5, 'Color', colors(ti,:));
    end
    title(pax, 'Normalized Gain Overlay');
    rlim(pax,[-20 0]); thetalim(pax,[-90 90]);
    pax.ThetaZeroLocation = 'top'; pax.ThetaDir = 'clockwise';
    grid(pax,'on');    
    
    %% 3. Scan Roll-off Fit
    subplot(1,4,3);
    norm_dB  = peak_gains - peak_gains(1);
    norm_lin = 10.^(norm_dB/10);
    
    idx_fit = 2 : length(theta_steer);
    log_cos = log(cos(deg2rad(theta_steer(idx_fit))));
    log_g   = log(norm_lin(idx_fit));
    n_fit   = (log_cos * log_g') / (log_cos * log_cos');
    
    theta_fine  = linspace(0, 60, 500);
    fit_curve   = peak_gains(1) + 10*log10(cos(deg2rad(theta_fine)).^n_fit);

    plot(theta_fine, fit_curve, 'b-', 'LineWidth', 2); hold on;
    scatter(theta_steer, peak_gains, 60, 'ko', 'LineWidth', 1.5);
    grid on; title(['Roll-off: cos(\theta)^{', num2str(n_fit, '%.2f'), '}']);
    xlabel('\theta [deg]'); ylabel('Gain [dBi]');
    legend('Fit', 'Simulated', 'Location', 'southwest');

    %% 4. Lorentzian: Amplitude vs Phase
    subplot(1,4,4);
    [sorted_P, idx_s] = sort(all_P);
    plot(sorted_P, all_A(idx_s), 'r.-', 'LineWidth', 1.5); grid on;
    title('Lorentzian: A vs \phi'); xlabel('Phase [deg]'); ylabel('Amplitude');
end

%% FINAL COMPARISON: Sidelobe Level vs. Angle
figure('Name', 'SLL Comparison', 'Color', 'w', 'Position', [200 200 600 400]);
markers = {'-o', '-s', '-^'};
hold on;
for b = 1:length(bits_to_test)
    plot(theta_steer, sll_all_bits(b,:), markers{b}, 'LineWidth', 2, ...
        'DisplayName', sprintf('%d-Bit Quantization', bits_to_test(b)));
end
grid on; grid minor;
xlabel('Steering Angle [deg]'); ylabel('Peak Sidelobe Level [dBc]');
title('Sidelobe Level (SLL) Performance');
legend('Location', 'northeast');
ylim([-20 0]);