%% MATLAB Code from Sensor Array Analyzer App
% Generated by MATLAB 25.2 and Phased Array System Toolbox 25.2
% Generated on 30-Mar-2026 13:31:57

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',9,...
    'ArrayAxis','y');
% The multiplication factor for lambda units to meter conversion
Array.ElementSpacing = 0.5*0.03;
Array.Taper = ones(1,9).';

% Create a cosine antenna element
Elem = phased.CosineAntennaElement;
Elem.CosinePower = [2 2];
Elem.FrequencyRange = [0 10000000000];
Array.Element = Elem;
% Assign Frequencies and Propagation Speed
Frequency = 10000000000;
PropagationSpeed = 300000000;

%% Tuning
% Parameters
lambda = 3e8 / Frequency;
d = Array.ElementSpacing;
numElements = getNumElements(Array);
element_idx = (0 : numElements - 1)';

% Lorentzian
fr_sweep = linspace(8e9,12e9, 10000);
delta_f = 0.05 * fr_sweep;
R = (2 + fr_sweep) ./ (fr_sweep.^2 - Frequency^2 + 1i * delta_f .* Frequency);

% Amplitude and phase responses
amp_response = 1 - (abs(R) * 100e6);       
phase_response = 2 * angle(R) + pi;           

% Scan
theta_steer = 0 : 10 : 60;   
theta_scan = linspace(-90, 90, 3601);
peak_gains = zeros(size(theta_steer));
errors = zeros(size(theta_steer));
actual_deg = zeros(size(theta_steer));

% Pre-calculate Steering Vectors and Element Factor
EF = step(Elem, Frequency, [theta_scan; zeros(size(theta_scan))]).'; 
SV_matrix = exp(1i * 2*pi * (d/lambda) * element_idx * sin(deg2rad(theta_scan)));

% Storage for polar plotting
patterns_to_plot = zeros(length(theta_steer), length(theta_scan));

for ti = 1 : length(theta_steer)
    theta_steer_rad = deg2rad(theta_steer(ti));
    req_phase_vec = -2*pi * (d/lambda) * element_idx * sin(theta_steer_rad);

    w = zeros(numElements, 1);
    for el = 1 : numElements
        % Find nearest phase in Lorentzian sweep using mod 2*pi
        target = mod(req_phase_vec(el), 2*pi);
        [~, idx] = min(abs(mod(phase_response, 2*pi) - target));

        % Complex weights in x + iy form
        A = amp_response(idx);
        P = phase_response(idx);
        w(el) = A * (cos(P) + 1i*sin(P));
    end

    % Calculate Pattern
    AF_total = abs(w.' * SV_matrix) .* (EF);
    [max_val, peak_idx] = max(AF_total);
    
    peak_gains(ti)  = max_val;
    actual_deg(ti)  = theta_scan(peak_idx);
    errors(ti)      = abs(theta_steer(ti) - actual_deg(ti));
    patterns_to_plot(ti, :) = AF_total;
end

%% --- FIGURE 1: Pointing Angle Error ---
figure('Name', 'Pointing Angle Error', 'Color', 'w');
scatter(theta_steer, errors, 120, 'filled', ...
    'MarkerFaceColor', [0.216 0.541 0.867], 'MarkerEdgeColor', 'k');
grid on; grid minor;
xlabel('Intended pointing angle [deg]');
ylabel('|Intended - Actual| [deg]');
title('Pointing Angle Error at 10 GHz (f_r tunable 8–12 GHz)');
xticks(theta_steer);

%% --- FIGURE 2: Polar Normalized Gain Overlay ---
figure('Name', 'Polar Overlay', 'Color', 'w');

% Create the polar axes object
pax = polaraxes;
hold(pax, 'on');
norm_ref = peak_gains(1); 
colors = hsv(length(theta_steer) + 2); 

for ti = 1 : length(theta_steer)
    pattern_dB = 20*log10(patterns_to_plot(ti, :) / norm_ref);
    polarplot(pax, deg2rad(theta_scan), pattern_dB, 'LineWidth', 1.5, 'Color', colors(ti,:));
end

title('On Axis \phi = 0^\circ - Normalized Gain Overlay');

% Set limits and ticks using the axes handle
rlim(pax, [-20 5]); 
rticks(pax, [-20 -15 -10 -5 0 5]);
thetalim(pax, [-90 90]); 
thetaticks(pax, -90:30:90);

pax.ThetaZeroLocation = 'top';
pax.ThetaDir = 'clockwise';
grid(pax, 'on');

%% --- FIGURE 3: Gain [dBi] vs Theta with Curve Fit ---
figure('Name', 'Scan Roll-off Fit', 'Color', 'w');
offset = 22.7 - 20*log10(peak_gains(1)); 
peak_dBi = 20*log10(peak_gains) + offset;

norm_ratios = peak_gains / peak_gains(1);
idx_fit = 2 : length(theta_steer); 
log_cos = log(cos(deg2rad(theta_steer(idx_fit))));
log_g   = log(norm_ratios(idx_fit));
n_fit   = (log_cos * log_g') / (log_cos * log_cos'); 

theta_fine = linspace(0, 60, 500);
fit_curve_dBi = peak_dBi(1) + 20*log10(cos(deg2rad(theta_fine)).^n_fit);

plot(theta_fine, fit_curve_dBi, 'b-', 'LineWidth', 2); hold on;
scatter(theta_steer, peak_dBi, 80, 'ko', 'LineWidth', 1.5);
grid on; xlabel('\theta [deg]'); ylabel('Gain [dBi]');
title(['On Axis \phi = 0^\circ - \cos(\theta)^{', num2str(n_fit, '%.2f'), '} Fit']);
legend(['\cos(\theta)^{', num2str(n_fit, '%.2f'), '} fit'], 'Simulated');

fprintf('Fitted roll-off constant n = %.4f\n', n_fit);