%% MATLAB Code from Sensor Array Analyzer App
% Generated by MATLAB 25.2 and Phased Array System Toolbox 25.2
% Generated on 30-Mar-2026 13:31:57

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',9,'ArrayAxis','y');
Array.ElementSpacing = 0.5*0.03;
Array.Taper = ones(1,9).';

% Create a cosine antenna element
Elem = phased.CosineAntennaElement;
Elem.CosinePower = [2.25 2.25];
Elem.FrequencyRange = [0 10000000000];
Array.Element = Elem;

% Frequencies and Propagation Speed
Frequency = 10000000000;
PropagationSpeed = 300000000;

%% Setup
lambda      = 3e8 / Frequency;
d           = Array.ElementSpacing;
numElements = getNumElements(Array);
element_idx = (0 : numElements-1)';
f           = Frequency;

% Symbolic variable
syms fr positive

% Scan setup
theta_steer      = 0 : 15 : 60;
theta_scan       = -90 : 0.1 : 90;
peak_gains       = zeros(size(theta_steer));
errors           = zeros(size(theta_steer));
actual_deg       = zeros(size(theta_steer));
patterns_to_plot = zeros(length(theta_steer), length(theta_scan));

sv = phased.SteeringVector('SensorArray', Array,...
    'PropagationSpeed', PropagationSpeed, ...
    'NumPhaseShifterBits', 0);

%% Main loop — continuous tuning 8 to 12 GHz
for ti = 1 : length(theta_steer)
    w_continuous = sv(Frequency, [theta_steer(ti); 0]);

    w = zeros(numElements, 1);
    for el = 1 : numElements
        % Required phase in degrees
        phi_req_deg = rad2deg(angle(w_continuous(el)));

        % Solve for fr that achieves phi_req at 10 GHz within [8, 12] GHz
        eqn    = ((2*angle((2 + fr)./(fr^2 - f^2 + 1i*0.05*fr*f)) + pi)*180/pi) ...
                 == phi_req_deg;
        assume(fr,'positive');
        fr_sol = (vpasolve(eqn,fr));

        % Clamp to nearest boundary (phase quantization limit)
         if isempty(fr_sol)
            if phi_req_deg < 0
                fr_sol = 8e9;
            else
                fr_sol = 12e9;
            end
        end

        if fr_sol < 8e9
            fr_sol = 8e9;
        elseif fr_sol > 12e9
            fr_sol = 12e9;
        end

        fprintf('    El %d:, phase=%.2f, fr=%.2f\n', el, phi_req_deg, fr_sol);

        % Compute R at solved
        R_el    = (2 + fr_sol) / (fr_sol^2 - f^2 + 1i*0.05*fr_sol*f);
        Amp     = 1 - (abs(R_el) * 100e6);
        Phas    = 2 * angle(R_el) + pi;

        real_part = Amp * cos(Phas);
        imag_part = Amp * sin(Phas);
        w(el)     = real_part + 1i * imag_part;
    end

    % Peak directivity at intended steering angle — absolute dBi
    peak_gains(ti) = pattern(Array, Frequency, theta_steer(ti), 0, ...
                         'PropagationSpeed', PropagationSpeed, ...
                         'Type', 'directivity', ...
                         'weights', w);

    % Full pattern in powerdb for polar plot
    AF_total               = pattern(Array, Frequency, theta_scan, 0, ...
                                 'PropagationSpeed', PropagationSpeed, ...
                                 'Type', 'powerdb', ...
                                 'weights', w).';
    [~, peak_idx]          = max(AF_total);
    actual_deg(ti)         = theta_scan(peak_idx);
    errors(ti)             = abs(theta_steer(ti) - actual_deg(ti));
    patterns_to_plot(ti,:) = AF_total;
end

%% FIGURE 1: Pointing Angle Error (part a)
figure('Name', 'Pointing Angle Error', 'Color', 'w');
scatter(theta_steer, errors, 120, 'filled', ...
    'MarkerFaceColor', [0.216 0.541 0.867], 'MarkerEdgeColor', 'k');
grid on; grid minor;
xlabel('Intended pointing angle [deg]');
ylabel('|Intended - Actual| [deg]');
title('Pointing Angle Error at 10 GHz (f_r tunable 8–12 GHz)');
xticks(theta_steer);

%% FIGURE 2: Polar Normalized Gain Overlay (part b)
figure('Name', 'Polar Overlay', 'Color', 'w');
pax    = polaraxes;
hold(pax, 'on');
colors = turbo(length(theta_steer));
for ti = 1 : length(theta_steer)
    % Normalise to 0 deg beam peak — subtract 0 deg max in powerdb
    pattern_norm = patterns_to_plot(ti,:) - max(patterns_to_plot(1,:));
    polarplot(pax, deg2rad(theta_scan), pattern_norm, ...
        'LineWidth', 1.5, 'Color', colors(ti,:));
end
title(pax, 'On Axis \phi = 0^\circ - Normalized Gain Overlay');
rlim(pax,[-20 0]); rticks(pax,[-20 -15 -10 -5 0]);
thetalim(pax,[-90 90]); thetaticks(pax,-90:30:90);
pax.ThetaZeroLocation = 'top';
pax.ThetaDir          = 'clockwise';
grid(pax,'on');

%% FIGURE 3: Scan Roll-off with cos(theta)^n fit (part b)
% Normalise to 0 deg — peak_gains in absolute dBi
norm_dB  = peak_gains - peak_gains(1);
norm_lin = 10.^(norm_dB/10);

idx_fit = 2 : length(theta_steer);
log_cos = log(cos(deg2rad(theta_steer(idx_fit))));
log_g   = log(norm_lin(idx_fit));
n_fit   = (log_cos * log_g') / (log_cos * log_cos');

theta_fine    = linspace(0, 60, 500);
fit_curve_dBi = peak_gains(1) + 10*log10(cosd(theta_fine).^n_fit);

figure('Name', 'Scan Roll-off Fit', 'Color', 'w');
plot(theta_fine, fit_curve_dBi, 'b-', 'LineWidth', 2); hold on;
scatter(theta_steer, peak_gains, 80, 'ko', 'LineWidth', 1.5);
grid on;
xlabel('\theta [deg]'); ylabel('Gain [dBi]');
title('Scan Roll Off');
legend(['\cos(\theta)^{' num2str(n_fit,'%.2f') '} fit'], 'Simulated', ...
    'Location', 'southwest');
fprintf('Fitted roll-off constant n = %.4f\n', n_fit);